# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# Site settings
title: Het Tinnen Soldaatje
email: kencoenen@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Het Tinnen Soldaatje brengt fijngevoelige muziek voor jonge kindjes
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
facebook: tinnensoldaatje1

sass:
    sass_dir: _sass
    style: compressed

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
