# ----
# Site

title: Tinnen Soldaatje
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.tinnensoldaatje.be" # the base hostname & protocol for your site
google_analytics_key: UA-4433792-3
google_maps_javascript_api_key:
disqus_shortname:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /images/siteicon.png
description: Tinnen Soldaatje brengt fijngevoelige muziek voor jonge kinderen.
author:
  name:
  email:
  twitter: # twitter username without the @ symbol

# -----
# Build

sass:
    sass_dir: _sass
    style: compressed

paginate: 4
paginate_path: "/advice/:num/"

collections:
  - "authors"

defaults:
  -
    scope:
      path: ""
    values:
      layout: page
      background_image_path: /assets/images/tekeningen/mannetje-rechts@0,25x.png
      image: /assets/images/tekeningen/struik-2@0,1x.png
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      call_to_action: Contact
      _options:
        content:
          width: 960
          height: 2000
      _comments:
        image: Shown in social shares and the advice list.
  -
    scope:
      path: ""
      type: "authors"
    values:
      _options:
        image:
          width: 440
          height: 440

permalink: pretty

jekyll-archives:
  enabled:
    - categories

plugins_dir:
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

gems:
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate

# -----------
# CloudCannon

call_to_actions:
  - Contact
  - Advice
  - Map

social_icons:
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - RSS

_comments:
  large_header: Toggles the size of the top banner.
  show_in_navigation: Toggles a link in the top banner.
  author: The staff member writing this post.
  call_to_action: Type of request shown at the bottom of this page.
  background_image_path: Image shown in the top banner, blank for the default.
  testimonials: Update, add or remove testimonials.
  map: Update the map location and display settings.
  latitude: Coordinates for the center marker on the map.
  longitude: Coordinates for the center marker on the map.
  zoom: The zoom level for the map.
  phone_extension: The digits after dialing the company phone.
  credentials: Shown as subtext on staff member summaries.
  contact_email_address: Address for the contact form to send to.
  new_window: Whether the link opens a new browser tab/window.
